apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hello-world-app
  name: hello-world-app
  namespace: hello-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world-app
    spec:
      containers:
      - image: ellenxujuan/go-web-hello-world:v0.1
        name: hello-world-app
        ports:
        - containerPort: 31080
