apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    k8s-app: hello-world-service
spec:
  type: NodePort
  ports:
  - name: hello-world-api
    port: 8083
    targetPort: 8083
    nodePort: 31080
  selector:
    app: hello-world
